# Cloudflare Pages 构建配置
# 文档: https://developers.cloudflare.com/pages/configuration/build-configuration/

# 构建配置
build:
  command: |
    corepack enable
    corepack prepare pnpm@10 --activate

    # Provide safe defaults for preview builds where Cloudflare env vars may be missing.
    # Production values (set in Cloudflare Pages) will override these.
    export SKIP_ENV_VALIDATION="${SKIP_ENV_VALIDATION:-true}"
    export DATABASE_URL="${DATABASE_URL:-postgresql://test:test@localhost:5432/test}"
    export NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL:-https://test.supabase.co}"
    export SUPABASE_SERVICE_KEY="${SUPABASE_SERVICE_KEY:-test-service-key}"
    export NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-test-secret-key-for-pages-preview}"
    export NEXTAUTH_URL="${NEXTAUTH_URL:-https://hearthbulter.pages.dev}"

    pnpm install --frozen-lockfile --prod=false
    pnpm build:cloudflare
  output_directory: .open-next

# 环境变量已通过 wrangler secret 配置：
# - DATABASE_URL
# - NEXTAUTH_SECRET
# 公开变量通过 wrangler.toml 配置
