#!/bin/bash

# Supabase 账户诊断脚本
# 帮助用户找到正确的账户和项目

echo "🔍 Supabase 账户诊断工具"
echo "========================="
echo ""

echo "🚨 关键发现"
echo "============="
echo "ant.wilson@supabase.com 不是你的账户"
echo "需要确认正确的账户信息和项目位置"
echo ""

echo "🎯 账户诊断步骤"
echo "================="

echo ""
echo "📱 步骤 1: 确认邮件来源"
echo "---------------------------"
echo "1. 仔细查看收到的暂停通知邮件"
echo "2. 确认邮件发件人地址"
echo "3. 检查邮件中的项目链接"
echo "4. 查看邮件中提到的账户信息"
echo ""
echo "📧 常见 Supabase 邮件发件人:"
echo "- noreply@supabase.com"
echo "- support@supabase.com"
echo "- accounts@supabase.com"
echo ""

echo "📱 步骤 2: 检查所有可能的账户"
echo "---------------------------------"
echo "1. 想一想你注册 Supabase 时使用的邮箱"
echo "2. 可能的账户:"
echo "   - 个人邮箱 (Gmail, Outlook 等)"
echo "   - 工作邮箱"
echo "   - GitHub 账户关联的邮箱"
echo "3. 尝试用这些邮箱登录 Supabase"
echo ""

echo "📱 步骤 3: 检查项目共享情况"
echo "--------------------------------"
echo "1. 项目可能被共享给了 ant.wilson@supabase.com"
echo "2. 但实际所有权在你的账户下"
echo "3. 检查是否有邀请通知"
echo "4. 查看项目成员权限"
echo ""

echo "📱 步骤 4: 搜索项目历史"
echo "-------------------------"
echo "1. 回忆创建项目时的账户"
echo "2. 检查项目部署历史记录"
echo "3. 查看本地配置文件中的信息"
echo "4. 搜索相关的账户信息"
echo ""

echo "📱 步骤 5: 检查 GitHub 集成"
echo "-----------------------------"
echo "1. Supabase 项目可能通过 GitHub OAuth 创建"
echo "2. 检查你的 GitHub 账户"
echo "3. 查看连接的第三方账户"
echo "4. 确认 GitHub 邮箱与 Supabase 一致"
echo ""

echo "🔍 快速诊断检查"
echo "==============="
echo ""

echo "📋 检查本地配置"
echo "================="
echo "1. 检查 .env 文件中的历史配置"
echo "2. 查看项目文档中的相关信息"
echo "3. 搜索代码库中的配置文件"
echo ""

echo "📋 检查项目链接"
echo "==============="
echo "1. 任何之前访问过的项目链接"
echo "2. 书签中的 Supabase 链接"
echo "3. 浏览器历史记录"
echo ""

echo "📋 检查邮件记录"
echo "==============="
echo "1. 搜索 'Supabase' 相关邮件"
echo "2. 查看项目创建确认邮件"
echo "3. 检查项目邀请通知"
echo ""

echo "🎯 紧急解决方案"
echo "================="

echo ""
echo "方案1: 找到正确账户 (推荐)"
echo "----------------------------"
echo "1. 用可能的邮箱逐一尝试登录"
echo "2. 检查每个账户下的项目"
echo "3. 找到 'health-butler' 或类似项目"
echo "4. 恢复或配置该项目"
echo ""

echo "方案2: 创建新项目 (快速)"
echo "--------------------------"
echo "1. 使用你的主要账户登录"
echo "2. 创建新的 Supabase 项目"
echo "3. 项目名称: health-butler-prod"
echo "4. 快速配置和部署"
echo ""

echo "方案3: 邮件支持 (如果无法确认)"
echo "--------------------------------"
echo "1. 联系 Supabase 支持"
echo "2. 提供暂停通知邮件的引用"
echo "3. 请求确认项目所有权"
echo "4. 获取项目访问权限"
echo ""

echo "📞 联系信息"
echo "============="
echo ""
echo "Supabase 支持:"
echo "- 邮箱: support@supabase.com"
echo "- 支持工单: https://supabase.com/support/tickets"
echo "- 文档: https://supabase.com/docs"
echo ""
echo "需要提供的信息:"
echo "- 暂停通知邮件的完整内容"
echo "- 项目可能的名称"
echo "- 你的 Supabase 账户信息"
echo "- 任何相关的项目链接"
echo ""

echo "🔧 本地检查工具"
echo "==============="
echo ""

echo "1. 检查环境变量历史:"
echo "   find . -name '*.env*' -type f"
echo ""
echo "2. 搜索项目引用:"
echo "   grep -r 'supabase\\|DATABASE_URL' . --include='*.ts' --include='*.js' --include='*.env*' 2>/dev/null | head -5"
echo ""
echo "3. 查看提交历史:"
echo "   git log --oneline --grep='supabase\\|database\\|DATABASE' | head -5"
echo ""

echo "📋 账户确认清单"
echo "==============="
echo "□ 确认邮件发件人地址"
echo "□ 检查可能的邮箱列表"
echo "□ 尝试登录各账户"
echo "□ 查看项目共享情况"
echo "□ 检查 GitHub 集成"
echo "□ 联系 Supabase 支持 (如需要)"
echo ""

echo "🎯 下一步行动"
echo "==============="
echo ""
echo "立即执行:"
echo "1. ✋ 停止当前的配置尝试"
echo "2. 🔍 确认正确的 Supabase 账户"
echo "3. 📂 找到正确的项目"
echo "4. ⚙️ 进行正确的配置"
echo ""
echo "如果找不到原项目:"
echo "1. 🆕 创建新的 Supabase 项目"
echo "2. 🔧 配置 Vercel 环境变量"
echo "3. 🗄️ 运行数据库迁移"
echo "4. ✅ 验证应用功能"
echo ""

echo "⏱️  预计解决时间"
echo "================="
echo "- 账户确认: 5-10 分钟"
echo "- 项目查找: 5-10 分钟"
echo "- 新项目创建: 5 分钟 (如果需要)"
echo "- 配置和部署: 10-15 分钟"
echo ""
echo "总计: 15-40 分钟 (取决于找到原项目的速度)"
echo ""

echo "🎉 账户确认后，你的应用将很快恢复正常！"
echo ""
echo "💡 建议: 找到正确账户后再进行配置，避免设置错误"
