#!/bin/bash

# Supabase 紧急修复脚本
# 处理项目找不到或已删除的情况

echo "🚨 Supabase 紧急修复指南"
echo "==========================="
echo ""

echo "🔍 当前问题分析"
echo "================="
echo "项目列表中找不到 'health-butler' 项目"
echo ""
echo "可能的原因:"
echo "1. 项目已超过 90 天暂停期被永久删除"
echo "2. 项目名称不同或不匹配"
echo "3. 账户或组织切换问题"
echo "4. 项目权限问题"
echo ""

echo "🎯 紧急处理方案"
echo "================="
echo ""

echo "📱 步骤 1: 检查账户和组织"
echo "------------------------------"
echo "1. 确认登录的是正确账户 (ant.wilson@supabase.com)"
echo "2. 检查右上角的组织选择器"
echo "3. 切换到正确的组织 (如果有多个)"
echo "4. 重新加载项目列表 (F5)"
echo ""

echo "📱 步骤 2: 搜索项目"
echo "-----------------------"
echo "1. 在 Supabase Dashboard 中使用搜索功能"
echo "2. 搜索 'health-butler' 或 'health'"
echo "3. 检查是否有名称相似的项目"
echo "4. 查看包括归档项目的列表"
echo ""

echo "📱 步骤 3: 检查邮件和通知"
echo "-----------------------------"
echo "1. 检查 ant.wilson@supabase.com 的邮件"
echo "2. 查找 Supabase 发送的项目删除通知"
echo "3. 确认项目是否已永久删除"
echo "4. 检查是否有数据下载链接"
echo ""

echo "🎯 如果项目已被删除 - 紧急创建新项目"
echo "========================================"
echo ""

echo "📱 步骤 4: 创建新的 Supabase 项目 (5分钟)"
echo "------------------------------------------"
echo "1. 在 Supabase Dashboard 点击 'New project'"
echo "2. 项目配置:"
echo "   - 项目名称: health-butler-v2"
echo "   - 数据库密码: [生成强密码，保存到密码管理器]"
echo "   - 区域: Northeast Asia (Seoul)"
echo "3. 点击 'Create new project'"
echo "4. 等待 2-3 分钟数据库初始化"
echo ""

echo "📱 步骤 5: 配置新项目连接 (3分钟)"
echo "-------------------------------------"
echo "1. 项目创建完成后进入项目设置"
echo "2. 点击 'Settings' → 'Database'"
echo "3. 复制 'Connection string' → 'URI'"
echo "4. 确认使用 '.pooler.' 连接字符串"
echo ""

echo "📱 步骤 6: 更新 Vercel 环境变量 (5分钟)"
echo "------------------------------------------"
echo "1. 访问: https://vercel.com/dashboard"
echo "2. 进入 'HearthBulter' 项目"
echo "3. 点击 'Settings' → 'Environment Variables'"
echo "4. 更新以下变量:"
echo ""

echo "🔧 紧急环境变量配置"
echo "===================="
echo "DATABASE_URL: [从新项目复制的连接字符串]"
echo "NEXTAUTH_SECRET: ntZl8q4ZA3c2LIWf+rpJKTDBYJzYeUpjCEY/X0Jy5Ho="
echo "NEXTAUTH_URL: https://hearth-bulter.vercel.app"
echo "NEXT_PUBLIC_ALLOWED_ORIGINS: https://hearth-bulter.vercel.app"
echo "UPSTASH_REDIS_REST_URL: https://teaching-eagle-34132.upstash.io"
echo "UPSTASH_REDIS_REST_TOKEN: AYVUAAIncDJlNTBmMjlkMDBhMDY0MTU1OWQ2YmVjM2Q2N2Y2MmI3ZHAyMzQxMzI"
echo ""

echo "📱 步骤 7: 运行数据库迁移 (5分钟)"
echo "------------------------------------"
echo "1. 等待 Vercel 重新部署完成"
echo "2. 在项目根目录运行:"
echo "   npm run deploy:database"
echo "3. 验证迁移成功:"
echo "   npx prisma migrate status"
echo ""

echo "📱 步骤 8: 验证新项目功能 (5分钟)"
echo "------------------------------------"
echo "1. 运行完整部署验证:"
echo "   npm run check:deployment https://hearth-bulter.vercel.app"
echo "2. 手动测试:"
echo "   - 用户注册功能"
echo "   - 用户登录功能"
echo "   - 数据库操作"
echo ""

echo "🛡️ 数据恢复选项"
echo "==============="
echo ""

echo "如果原项目数据重要:"
echo "1. 检查邮件中的数据下载链接"
echo "2. 从 Supabase 下载备份数据"
echo "3. 手动导入到新项目中"
echo "4. 验证数据完整性"
echo ""

echo "🎯 快速恢复时间线"
echo "================="
echo "- 新项目创建: 5 分钟"
echo "- 连接配置: 3 分钟"
echo "- 环境变量更新: 5 分钟"
echo "- Vercel 重新部署: 5 分钟"
echo "- 数据库迁移: 5 分钟"
echo "- 功能验证: 5 分钟"
echo "总计: 约 28 分钟"
echo ""

echo "🔗 紧急联系和支持"
echo "=================="
echo ""
echo "Supabase 支持:"
echo "- 官方文档: https://supabase.com/docs"
echo "- 支持工单: https://supabase.com/support/tickets"
echo "- 社区论坛: https://github.com/supabase/supabase/discussions"
echo ""
echo "Vercel 支持:"
echo "- 文档: https://vercel.com/docs"
echo "- 状态页: https://www.vercel-status.com/"
echo "- 帮助中心: https://vercel.com/help"
echo ""

echo "📋 紧急恢复检查清单"
echo "===================="
echo "✅ 确认原项目状态 (删除/暂停/其他)"
echo "✅ 创建新的 Supabase 项目"
echo "✅ 配置数据库连接字符串"
echo "✅ 更新 Vercel 环境变量"
echo "✅ 运行数据库迁移"
echo "✅ 验证所有功能正常"
echo "✅ 用户可以注册和登录"
echo "✅ API 端点返回 HTTP 200"
echo ""

echo "🎯 预期结果"
echo "============"
echo "✅ 应用正常工作"
echo "✅ 数据库连接正常"
echo "✅ 所有功能可用"
echo "✅ 系统健康分数 > 80%"
echo "✅ 用户可以正常使用"
echo ""

echo "⚠️ 重要提醒"
echo "============"
echo "⏰ 如果原项目被删除，数据可能无法恢复"
echo "💾 建议定期备份数据库"
echo "🔄 考虑升级到 Supabase Pro 避免暂停"
echo "📞 如需帮助，联系 Supabase 支持"
echo ""

echo "🎉 原项目无法恢复时，新项目将很快让你的应用重新上线！"
echo ""
echo "💡 运行此脚本可以重新查看详细步骤"
echo "🚀 按照指南操作，你的健康管家应用将快速恢复！"
