#!/bin/bash

# Supabase 项目恢复脚本
# 指导用户恢复暂停的 Supabase 项目

echo "🔄 Supabase 项目恢复指南"
echo "========================"
echo ""

echo "🚨 当前问题:"
echo "health-butler 项目因 7 天不活跃被自动暂停"
echo "项目将在 90 天后永久删除"
echo "需要立即恢复以保存数据和功能"
echo ""

echo "🎯 立即恢复步骤 (5分钟)"
echo "========================="

echo ""
echo "📱 步骤 1: 访问 Supabase Dashboard"
echo "----------------------------------------"
echo "1. 在浏览器中访问: https://supabase.com/dashboard"
echo "2. 使用你的账户登录 (ant.wilson@supabase.com)"
echo "3. 查看项目列表，找到 'health-butler' 项目"
echo "4. 项目状态应该显示为 'Paused'"
echo ""

echo "📱 步骤 2: 恢复项目"
echo "---------------------------"
echo "1. 点击 'health-butler' 项目进入项目详情"
echo "2. 查找 'Resume project' 或 'Unpause project' 按钮"
echo "3. 点击恢复按钮"
echo "4. 等待项目重新启动 (通常 1-2 分钟)"
echo ""

echo "📱 步骤 3: 验证恢复状态"
echo "----------------------------"
echo "1. 项目恢复后，状态会变为 'Active'"
echo "2. 可以正常访问数据库和 API"
echo "3. 检查项目设置和数据完整性"
echo ""

echo "🎯 恢复完成后 - 更新应用配置"
echo "==============================="
echo ""

echo "📝 步骤 4: 获取当前数据库连接"
echo "---------------------------------"
echo "1. 进入恢复后的项目"
echo "2. 点击左侧菜单 'Settings'"
echo "3. 选择 'Database' 标签页"
echo "4. 找到 'Connection string' 部分"
echo "5. 复制 'URI' 连接字符串"
echo "⚠️  确保使用 '.pooler.' 连接"
echo ""

echo "📝 步骤 5: 更新 Vercel 环境变量"
echo "-----------------------------------"
echo "1. 访问: https://vercel.com/dashboard"
echo "2. 进入 'HearthBulter' 项目"
echo "3. 点击 'Settings' → 'Environment Variables'"
echo "4. 更新以下变量:"
echo ""

echo "🔧 环境变量更新清单:"
echo "======================"
echo "DATABASE_URL: [从步骤4复制的新连接字符串]"
echo "NEXTAUTH_SECRET: ntZl8q4ZA3c2LIWf+rpJKTDBYJzYeUpjCEY/X0Jy5Ho="
echo "NEXTAUTH_URL: https://hearth-bulter.vercel.app"
echo "NEXT_PUBLIC_ALLOWED_ORIGINS: https://hearth-bulter.vercel.app"
echo "UPSTASH_REDIS_REST_URL: https://teaching-eagle-34132.upstash.io"
echo "UPSTASH_REDIS_REST_TOKEN: AYVUAAIncDJlNTBmMjlkMDBhMDY0MTU1OWQ2YmVjM2Q2N2Y2MmI3ZHAyMzQxMzI"
echo ""

echo "📝 步骤 6: 等待重新部署"
echo "-----------------------------"
echo "1. 环境变量保存后 Vercel 自动重新部署"
echo "2. 等待 3-5 分钟部署完成"
echo "3. 检查部署状态"
echo ""

echo "📝 步骤 7: 验证应用功能"
echo "---------------------------"
echo "运行验证命令:"
echo "npm run check:deployment https://hearth-bulter.vercel.app"
echo ""

echo "🛡️ 防止未来暂停的措施"
echo "======================"
echo ""

echo "方案1: 升级到 Pro (推荐)"
echo "-----------------------"
echo "1. 进入 Supabase 项目设置"
echo "2. 点击 'Billing' 或 'Usage'"
echo "3. 选择 Pro 计划"
echo "4. 优点:"
echo "   - 项目不会因不活跃而暂停"
echo "   - 更高的资源限制"
echo "   - 更好的性能"
echo "   - 专业支持"
echo ""

echo "方案2: 定期活跃策略"
echo "--------------------"
echo "1. 每 6 天访问一次项目"
echo "2. 运行简单的数据库查询"
echo "3. 设置定期维护提醒"
echo ""

echo "方案3: 自动活跃脚本"
echo "--------------------"
echo "创建 cron job 定期访问:"
echo "0 0 */5 * * * curl -s https://your-api-endpoint/health"
echo "每 5 天执行一次健康检查"
echo ""

echo "⏱️  恢复时间估算"
echo "=================="
echo "- 项目恢复: 1-2 分钟"
echo "- 配置更新: 5 分钟"
echo "- Vercel 重新部署: 5 分钟"
echo "- 功能验证: 5 分钟"
echo "总计: 约 15-20 分钟"
echo ""

echo "🔗 重要链接"
echo "============"
echo "- Supabase Dashboard: https://supabase.com/dashboard"
echo "- Vercel Dashboard: https://vercel.com/dashboard"
echo "- 应用验证: npm run check:deployment https://hearth-bulter.vercel.app"
echo ""

echo "🚨 重要提醒"
echo "============"
echo "⏰ 项目恢复有 90 天时间限制"
echo "💾 确保定期备份数据"
echo "🔄 考虑升级到 Pro 计划避免未来问题"
echo "📞 如有问题联系 Supabase 支持"
echo ""

echo "🎯 预期恢复结果"
echo "================"
echo "✅ Supabase 项目恢复正常 (Active)"
echo "✅ 数据库连接正常"
echo "✅ 应用 API 端点返回 HTTP 200"
echo "✅ 用户可以注册和登录"
echo "✅ 系统健康分数 > 80%"
echo ""

echo "🎉 项目恢复完成后，你的应用将重新完全可用！"
echo ""
echo "💡 提示: 如果恢复过程中遇到问题，可以运行这个脚本重新查看详细步骤"
echo "📞 需要帮助时，查看 Vercel 和 Supabase 的项目日志"
